import MetaTrader5 as mt5

# MT5 Connection Settings
MT5_ACCOUNT = "YOUR_ACCOUNT"
MT5_PASSWORD = "YOUR_PASSWORD"
MT5_SERVER = "YOUR_BROKER"

# Trading Settings
RISK_PERCENT = 1
SYMBOL = "XAUUSD"
TIMEFRAMES = [mt5.TIMEFRAME_M15, mt5.TIMEFRAME_H1, mt5.TIMEFRAME_H4, mt5.TIMEFRAME_D1]

# API Settings
TWITTER_API_KEY = "YOUR_API_KEY"
TWITTER_API_SECRET = "YOUR_API_SECRET"
TWITTER_ACCESS_TOKEN = "YOUR_ACCESS_TOKEN"
TWITTER_ACCESS_SECRET = "YOUR_ACCESS_SECRET"
